language: node_js

node_js:
 - "7"
 - "6"

cache: yarn

# This normally isn't necessary, but since we're specifying an explicit install step,
# we also need to explicitly install Yarn.
before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH=$HOME/.yarn/bin:$PATH

install:
 - yarn install
 - cd example && yarn install
 - cd ..

script:
 - npm run lint
 - npm test
